# Generated by Django 4.0.4 on 2022-05-18 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core2', '0003_remedio_stock_alter_remedio_marca'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
