# Generated by Django 4.0.4 on 2022-05-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core2', '0006_producto_descripcion_producto_marca_producto_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(default='disponible', max_length=20, verbose_name='Estado del remedio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.CharField(max_length=20, verbose_name='Stock'),
        ),
    ]
