# Generated by Django 4.0.4 on 2022-05-18 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoria_remedio'),
    ]

    operations = [
        migrations.AddField(
            model_name='remedio',
            name='stock',
            field=models.CharField(default=1, max_length=20, verbose_name='stock'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='remedio',
            name='marca',
            field=models.CharField(max_length=20, verbose_name='Laboratorio'),
        ),
    ]
