# Generated by Django 4.0.4 on 2022-05-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_paciente_alter_producto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('numero', models.CharField(max_length=64, verbose_name='Numero')),
                ('remedio', models.CharField(max_length=30, verbose_name='Remedio')),
                ('estado', models.CharField(max_length=30, verbose_name='Estado')),
            ],
        ),
    ]
