# Generated by Django 4.0.4 on 2022-05-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_producto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('correo', models.CharField(max_length=64, verbose_name='Correo')),
                ('numero', models.CharField(max_length=64, verbose_name='Numero')),
                ('diagnostico', models.CharField(max_length=40, verbose_name='Diagnostico paciente')),
            ],
        ),
    ]
