# Generated by Django 4.0.4 on 2022-05-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_paciente_alter_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='receta',
            field=models.CharField(default='hola', max_length=64, verbose_name='Diagnostico paciente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='diagnostico',
            field=models.CharField(max_length=64, verbose_name='Diagnostico paciente'),
        ),
    ]
