# Generated by Django 4.0.4 on 2022-05-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_paciente_receta_alter_paciente_diagnostico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='receta',
            field=models.CharField(max_length=64, verbose_name='Receta del paciente'),
        ),
    ]
